// <auto-generated />
namespace MakeYourPizza.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_foreign_key_property_to_Order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_foreign_key_property_to_Order));
        
        string IMigrationMetadata.Id
        {
            get { return "201612231011522_Add_foreign_key_property_to_Order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
